"""
BoardRenderer - Markdown 自动投影生成器
从数据库读取项目/任务状态，自动生成 BOARD.md 和任务卡 md 文件。
替代人工维护，实现数据库真源 -> Markdown 投影。
"""
from __future__ import annotations

import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from .database import get_conn


# ============================================================
# 常量
# ============================================================

AUTO_GENERATED_WARNING = (
    "> **AUTO-GENERATED by FoxBoard.** "
    "任务状态由系统维护，请勿手动修改。\n"
)

HUMAN_NOTES_MARKER = "<!-- 人工备注区 - 以下内容保留，不被自动覆盖 -->"


# ============================================================
# 数据库读取
# ============================================================

def get_tasks_by_project(project_id: str) -> List[Dict[str, Any]]:
    """从数据库读取某项目的所有任务"""
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, title, description, status, priority, "
        "assignee_id, project_id, tags, started_at, depends_on, "
        "created_at, updated_at, completed_at "
        "FROM tasks WHERE project_id = ? OR ? = '*' "
        "ORDER BY priority DESC, created_at ASC",
        (project_id, project_id),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def get_task_by_id(task_id: str) -> Optional[Dict[str, Any]]:
    """按 ID 读取单个任务"""
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, title, description, status, priority, "
        "assignee_id, project_id, tags, started_at, depends_on, "
        "created_at, updated_at, completed_at "
        "FROM tasks WHERE id = ?",
        (task_id,),
    )
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def get_project(project_id: str) -> Optional[Dict[str, Any]]:
    """读取项目信息"""
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM projects WHERE id = ?", (project_id,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


# ============================================================
# BOARD.md 生成
# ============================================================

def _priority_label(p: int) -> str:
    labels = {0: "P0", 1: "P1", 2: "P2", 3: "P3", 4: "P4"}
    return labels.get(p, "P%d" % p)


def _status_icon(status: str) -> str:
    icons = {
        "TODO": "📋", "DOING": "🔵", "REVIEW": "🟡",
        "DONE": "✅", "BLOCKED": "🚫",
    }
    return icons.get(status, "")


def _group_by_status(tasks: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    groups: Dict[str, List[Dict[str, Any]]] = {
        "TODO": [], "DOING": [], "REVIEW": [],
        "DONE": [], "BLOCKED": [],
    }
    for t in tasks:
        groups.setdefault(t["status"], []).append(t)
    return groups


def _extract_phase(task: Dict[str, Any]) -> Optional[str]:
    """从 tags/title/description 中提取 Phase 信息"""
    text = " ".join([
        task.get("tags") or "",
        task.get("title") or "",
        task.get("description") or "",
    ])
    m = re.search(r"Phase\s*(\d+)", text, re.IGNORECASE)
    if m:
        num = int(m.group(1))
        if num <= 6:
            return "archived"
        return "Phase %d (v0.%d.0)" % (num, num)
    return None


def _render_task_row(task: Dict[str, Any]) -> str:
    """渲染单条任务摘要行（用于泳道）"""
    tid = task["id"]
    title = task["title"]
    assignee = task["assignee_id"] or "—"
    priority = _priority_label(task["priority"])
    depends = task["depends_on"] or "—"
    status = task["status"]
    return (
        "| `%s` | %s | %s | %s | %s | %s |"
        % (tid, title, assignee, priority, depends, status)
    )


def _render_phase_block(
    phase_name: str,
    tasks: List[Dict[str, Any]],
    archived: bool = False,
) -> str:
    """渲染单个 Phase 的任务块"""
    icon = "✅" if archived else "🔥"
    groups = _group_by_status(tasks)
    lines: List[str] = []
    lines.append("\n### %s %s\n" % (icon, phase_name))

    if not any(groups.values()):
        lines.append("> （暂无任务）\n")
        return "\n".join(lines)

    for status in ["TODO", "DOING", "REVIEW", "DONE", "BLOCKED"]:
        col_tasks = groups.get(status, [])
        if not col_tasks:
            continue
        status_icon = _status_icon(status)
        lines.append(
            "#### %s %s（%d个）\n"
            % (status_icon, status, len(col_tasks))
        )
        lines.append(
            "| ID | 任务名 | 负责人 | 优先级 | 依赖 | 状态 |"
        )
        lines.append("|---|---|---|---|---|---|")
        for t in col_tasks:
            lines.append(_render_task_row(t))
        lines.append("")
    return "\n".join(lines)


def generate_board_md(project_id: str, project_board_path: Path) -> str:
    """
    生成 BOARD.md 内容。
    project_board_path: 项目看板目录
    """
    tasks = get_tasks_by_project(project_id)
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M")

    # 按 Phase 分组
    phase_groups: Dict[str, List[Dict[str, Any]]] = {}
    active_tasks: List[Dict[str, Any]] = []
    archived_tasks: List[Dict[str, Any]] = []

    for t in tasks:
        phase = _extract_phase(t)
        if phase == "archived":
            archived_tasks.append(t)
        elif phase:
            phase_groups.setdefault(phase, []).append(t)
        else:
            active_tasks.append(t)

    # 生成 BOARD.md 头部
    header = (
        "# BOARD.md - FoxBoard 任务看板\n\n"
        "> **唯一的任务调度中心**。花火写入任务，执行人读取并推进。\n"
        "> 更新日期：%s | 由 board_renderer.py 自动投影\n\n"
        "---\n\n"
        "## 状态说明\n\n"
        "| 状态 | 含义 | 谁改 |\n"
        "|------|------|------|\n"
        "| `TODO` | 待执行 | 花火写入 |\n"
        "| `DOING` | 正在执行 | 执行人认领 |\n"
        "| `REVIEW` | 等黑狐审核 | 执行人完成后提交 |\n"
        "| `DONE` | 黑狐通过 + 花火确认 | 花火标记 |\n"
        "| `BLOCKED` | 需花火介入 | 执行人/花火标记 |\n\n"
        "### 状态流转\n"
        "```\n"
        "花火 TODO -> 执行人 DOING -> 执行人 REVIEW -> "
        "黑狐审核 PASS -> 花火 DONE\n"
        "```\n\n"
        "### 汇报链\n"
        "```\n"
        "白狐/青狐完成 -> FoxComms通知黑狐 -> 黑狐审核 -> "
        "FoxComms通知花火 -> 花火确认DONE\n"
        "黑狐自己完成 -> 自审 -> FoxComms通知花火\n"
        "```\n\n"
        "### 归档规则\n"
        "Phase 完成后任务卡移入 `tasks/archive/phaseN/`，"
        "BOARD.md 只保留归档索引。\n\n---\n"
    ) % now

    lines: List[str] = [header]

    # 活跃 Phase
    for phase in sorted(phase_groups.keys()):
        lines.append(_render_phase_block(phase, phase_groups[phase]))

    # 无 Phase 归类的活跃任务
    if active_tasks:
        lines.append(_render_phase_block("其他活跃任务", active_tasks))

    # 已归档索引
    if archived_tasks:
        lines.append("\n### 📦 已归档任务\n")
        lines.append("| ID | 任务名 | 负责人 | 状态 |")
        lines.append("|---|---|---|---")
        for t in archived_tasks:
            lines.append(
                "| `%s` | %s | %s | %s |"
                % (t["id"], t["title"], t["assignee_id"] or "—", t["status"])
            )

    return "\n".join(lines)


# ============================================================
# 任务卡文件生成
# ============================================================

def _human_notes_only(content: str) -> str:
    """从任务卡内容中提取人工备注区"""
    marker = HUMAN_NOTES_MARKER
    if marker in content:
        idx = content.index(marker)
        return content[idx:]
    return ""


def _parse_task_description(desc: str) -> Dict[str, str]:
    """
    从任务描述中解析结构化字段。
    支持 Markdown 格式的 ## 字段名\\n内容\\n。
    """
    fields = {
        "goal": "## 目标",
        "criteria": "## 完成标准",
        "steps": "## 推荐实现步骤",
        "references": "## 参考文件",
        "deliverables": "## 交付物",
        "reviewer_notes": "## 审核提示（黑狐）",
        "reviewer": "## 审核人",
    }
    result: Dict[str, str] = {}
    remaining = desc

    for key, marker in fields.items():
        if marker in remaining:
            idx = remaining.index(marker)
            part = remaining[idx + len(marker):].strip()
            next_marker_idx = len(part)
            for next_key, next_marker in fields.items():
                if next_marker in part:
                    ni = part.index(next_marker)
                    if ni < next_marker_idx:
                        next_marker_idx = ni
            content_val = part[:next_marker_idx].strip()
            if key == "reviewer":
                result[key] = content_val.split("\n")[0].strip()
            else:
                result[key] = content_val
            remaining = remaining[:idx] + remaining[idx + len(marker) + next_marker_idx:]

    if not result:
        result["goal"] = desc or "（无描述）"
    return result


def generate_task_card(
    task: Dict[str, Any],
    project_board_path: Path,
) -> str:
    """
    生成单个任务的 TASK-XXX.md 文件。
    保留已有的人工备注区内容。
    """
    tid = task["id"]
    path = project_board_path / "tasks" / ("TASK-%s.md" % tid)

    existing_notes = ""
    if path.exists():
        existing_notes = _human_notes_only(path.read_text(encoding="utf-8"))

    desc = task.get("description") or ""
    parsed = _parse_task_description(desc)
    depends = task["depends_on"] or "无"
    p = task["priority"]
    priority_str = _priority_label(p)
    phase = _extract_phase(task) or "—"
    if phase == "archived":
        phase = "Phase 归档"
    status_icon = _status_icon(task["status"])
    assignee = task["assignee_id"] or "—"

    reviewer = parsed.get("reviewer", "黑狐")
    goal = parsed.get("goal", "（任务目标见任务卡详情）")
    criteria = parsed.get("criteria", "（完成标准见原始任务卡）")
    steps = parsed.get("steps", "（参考任务卡）")
    references = parsed.get("references", "（无）")
    deliverables = parsed.get("deliverables", "（参考原始任务卡）")
    reviewer_notes = parsed.get("reviewer_notes", "（参考原始任务卡）")

    lines: List[str] = []
    lines.append(AUTO_GENERATED_WARNING)
    lines.append("## 基本信息\n")
    lines.append("- **状态**: %s %s" % (status_icon, task["status"]))
    lines.append("- **负责人**: %s" % assignee)
    lines.append("- **审核人**: %s" % reviewer)
    lines.append("- **优先级**: %s" % priority_str)
    lines.append("- **Phase**: %s" % phase)
    lines.append("- **依赖**: %s" % depends)
    lines.append("")
    lines.append("## 目标")
    lines.append(goal)
    lines.append("")
    lines.append("## 完成标准")
    lines.append(criteria)
    lines.append("")
    lines.append("## 推荐实现步骤")
    lines.append(steps)
    lines.append("")
    lines.append("## 参考文件")
    lines.append(references)
    lines.append("")
    lines.append("## 交付物")
    lines.append(deliverables)
    lines.append("")
    lines.append("## 审核提示（黑狐）")
    lines.append(reviewer_notes)
    lines.append("")
    lines.append("---")
    lines.append(HUMAN_NOTES_MARKER)

    if existing_notes:
        notes_content = existing_notes.replace(HUMAN_NOTES_MARKER, "").strip()
        if notes_content:
            lines.append("\n%s\n" % notes_content)
    else:
        lines.append("\n（人工备注区 - 供花火/黑狐添加人工说明）\n")

    return "\n".join(lines)


# ============================================================
# 主渲染入口
# ============================================================

def render_project(project_id: str, project_board_path: Path) -> Dict[str, Any]:
    """
    对整个项目执行完整渲染。
    返回 {"board": board_content, "tasks": {task_id: content}, ...}
    """
    # 1. 生成 BOARD.md
    board_content = generate_board_md(project_id, project_board_path)

    # 2. 写入 BOARD.md
    board_path = project_board_path / "BOARD.md"
    board_path.write_text(board_content, encoding="utf-8")

    # 3. 生成并写入每个任务卡
    tasks = get_tasks_by_project(project_id)
    task_contents: Dict[str, str] = {}
    for t in tasks:
        content = generate_task_card(t, project_board_path)
        task_path = project_board_path / "tasks" / ("TASK-%s.md" % t["id"])
        task_path.write_text(content, encoding="utf-8")
        task_contents[t["id"]] = content

    return {
        "board": board_content,
        "tasks": task_contents,
        "board_path": str(board_path),
        "task_count": len(task_contents),
    }


# ============================================================
# CLI 入口
# ============================================================

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="FoxBoard Markdown 投影生成器")
    parser.add_argument("--project", default="foxboard", help="项目 ID")
    parser.add_argument(
        "--board-path",
        default=None,
        help="项目看板目录路径",
    )
    args = parser.parse_args()

    if args.board_path:
        board_path = Path(args.board_path)
    else:
        script_dir = Path(__file__).resolve().parent.parent
        default_board = script_dir.parent / "projects" / args.project
        if not default_board.exists():
            default_board = (
                Path.home()
                / ".openclaw"
                / "workspace"
                / "qinghu"
                / "projects"
                / args.project
            )
        board_path = default_board

    print("[BoardRenderer] 项目: %s" % args.project)
    print("[BoardRenderer] 看板路径: %s" % board_path)

    result = render_project(args.project, board_path)
    print(
        "[BoardRenderer] ✅ BOARD.md 已写入（%d 个任务卡已更新）"
        % result["task_count"]
    )
    print("[BoardRenderer]    %s" % result["board_path"])
